services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "localdev"
      POSTGRES_USER: "sltom"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - ./data/.astropy/:/nonexistent/.astropy
    ports:
      - "8080:8080"
    env_file:
      - ./local.env
  worker:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - ./data/.astropy/:/nonexistent/.astropy
    env_file:
      - ./local.env
    command: ["bash", "start_worker.sh"]