# Generated by Django 4.2.23 on 2025-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0002_alter_zooniversesubject_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Latest time in the light curve', null=True),
        ),
    ]
