# Generated by Django 4.2.23 on 2025-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0003_alter_zooniversesubject_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniverseclassification',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
