# Generated by Django 4.2.23 on 2025-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0004_alter_zooniverseclassification_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversetarget',
            name='aggregated_annotations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
