# Generated by Django 4.2.23 on 2025-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0005_zooniversetarget_aggregated_annotations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zooniversetarget',
            name='aggregated_annotations',
        ),
        migrations.AddField(
            model_name='zooniversesurvey',
            name='fetch_data_method',
            field=models.CharField(blank=True, choices=[('TESS', 'TESS')], max_length=10, null=True),
        ),
    ]
