# Generated by Django 4.2.23 on 2025-08-11 14:17

from django.db import migrations, models
import zooniverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0006_remove_zooniversetarget_aggregated_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zooniversetarget',
            name='generated_lightcurve_image',
            field=models.ImageField(null=True, upload_to=zooniverse.models.zooniversetarget_lightcurve_image_path),
        ),
    ]
