# Generated by Django 4.2.23 on 2025-08-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0007_zooniversetarget_generated_lightcurve_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooniverseSubjectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_set_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zooniversesubject',
            name='subject_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zooniverse.zooniversesubjectset'),
        ),
    ]
