# Generated by Django 4.2.23 on 2025-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooniverse', '0008_zooniversesubjectset_zooniversesubject_retired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooniversesubject',
            name='sequence',
            field=models.CharField(blank=True, help_text='Sector, data release, etc.', max_length=50, null=True),
        ),
    ]
